apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: phoenix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: booking-service
        image: 787169320414.dkr.ecr.us-east-1.amazonaws.com/phoenix-booking-service:asgardeo-distfix-20251120
        ports:
        - containerPort: 7104
        envFrom:
        - configMapRef:
            name: asgardeo-config
        env:
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://mongodb:27017/hotel-booking"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: phoenix-app
spec:
  selector:
    app: booking-service
  ports:
  - port: 80
    targetPort: 7104