apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: phoenix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: search-service
        image: 787169320414.dkr.ecr.us-east-1.amazonaws.com/phoenix-search-service
        ports:
        - containerPort: 7105
        env:
        - name: MONGODB_CONNECTION_STRING
          value: "mongodb://mongodb:27017/hotel-booking"
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: phoenix-app
spec:
  selector:
    app: search-service
  ports:
  - port: 80
    targetPort: 7105