apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: phoenix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 787169320414.dkr.ecr.us-east-1.amazonaws.com/phoenix-frontend-service:asgardeo-runtime-fix-20251119
        ports:
        - containerPort: 4173   # <--- CHANGED FROM 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: phoenix-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80            # Keep this 80 (Internal Cluster Port)
    targetPort: 4173    # <--- CHANGED: Connect to the container on 4173
    nodePort: 30001