apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: phoenix-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 787169320414.dkr.ecr.us-east-1.amazonaws.com/phoenix-frontend-service
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: phoenix-app
spec:
  type: NodePort  # <--- Exposed to outside
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001 # <--- Access via http://MASTER_IP:30001